baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "hugo-theme-docdock"

title = "Bitfan"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"


[params]
editURL = "https://github.com/vjeantet/bitfan/edit/master/docs/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = false # default is false
unfoldedMenus = ["start"] # set menu identifiers which should be displayed unfolded  
themeStyle = "flex"
# themeVariant = "green" # choose theme variant "green", "gold" , "blue" (default)


[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> <label>Github repo</label>"
identifier = "repo"
url = "https://github.com/vjeantet/bitfan"
weight = 1

[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download'></i> <label>Download</label>"
url = "https://github.com/vjeantet/bitfan/releases"
weight = 3

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> <label>Credits & Contributors</label>"
url = "/credits"
weight = 4